import type { RTICaseData } from '../case-model.ts';

export const ashaAppealCase: RTICaseData = {
  schemaVersion: '1.0',
  caseId: 'asha-appeal-supplement',
  source: 'synthetic',
  fictional: true,
  title: 'Highway repair and inspection records',
  citizenName: 'Asha',
  citizenGoal: 'Understand the records behind a fictional highway-repair contract.',
  scenario: 'One branch replied, another did not. Asha filed a branch-specific first appeal, received an FAA order, and later received a supplemental reply.',
  painPoint: 'The request branch, appeal number, FAA order, and later reply form one chronology, but only the substantive replies can answer the original questions.',
  filedOn: '2026-01-05',
  authority: 'Central Highway Works Directorate (fictional)',
  rootNodeId: 'asha-application',
  structureLabel: 'Split with appeal and later reply',
  tags: ['no reply', 'first appeal', 'supplemental reply'],
  questions: [
    { id: 'asha-q1', number: 1, title: 'Work order', text: 'Provide the signed work order and approved contract value.' },
    { id: 'asha-q2', number: 2, title: 'Inspection records', text: 'Provide inspection reports and material-test results.' },
    { id: 'asha-q3', number: 3, title: 'Measurement book', text: 'Provide the relevant measurement-book extracts.' },
    { id: 'asha-q4', number: 4, title: 'Penalty records', text: 'Provide penalty or payment-deduction orders, or a record stating none was issued.' },
  ],
  nodes: [
    { id: 'asha-application', kind: 'application', title: 'Original RTI application', summary: 'Asha asks four questions about one fictional road-work contract.', date: '2026-01-05', status: 'Filed', questionIds: ['asha-q1', 'asha-q2', 'asha-q3', 'asha-q4'] },
    { id: 'asha-contracts-registration', kind: 'registration', title: 'Contracts section', summary: 'Receives the work-order question.', date: '2026-01-07', status: 'Reply received', office: 'Contracts section', registrationNumber: 'DEMO/CHWD/R/E/26/00810', questionIds: ['asha-q1'] },
    { id: 'asha-contracts-reply', kind: 'reply', title: 'Contracts reply', summary: 'Provides the signed work order and contract value.', date: '2026-01-26', status: 'Substantive reply', registrationNumber: 'DEMO/CHWD/R/E/26/00810', questionIds: ['asha-q1'], documentIds: ['asha-contracts-doc'] },
    { id: 'asha-quality-registration', kind: 'registration', title: 'Quality and Finance section', summary: 'Receives inspection, measurement-book, and penalty questions.', date: '2026-01-07', status: 'Supplemental reply later received', office: 'Quality and Finance section', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', questionIds: ['asha-q2', 'asha-q3', 'asha-q4'] },
    { id: 'asha-no-reply', kind: 'no_reply', title: 'No reply available', summary: 'No substantive reply was available for this branch as of 5 February.', date: '2026-02-05', status: 'No reply observed', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', questionIds: ['asha-q2', 'asha-q3', 'asha-q4'] },
    { id: 'asha-appeal', kind: 'appeal', title: 'Branch-specific first appeal', summary: 'The appeal concerns only the unanswered Quality and Finance branch.', date: '2026-02-10', status: 'First appeal filed', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', appealNumber: 'DEMO/CHWD/A/E/26/00077', questionIds: ['asha-q2', 'asha-q3', 'asha-q4'] },
    { id: 'asha-appeal-order', kind: 'appeal_order', title: 'FAA direction', summary: 'The procedural order directs the CPIO to provide a reply. It is not proof that the requested records were supplied.', date: '2026-03-04', status: 'Appeal order received', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', appealNumber: 'DEMO/CHWD/A/E/26/00077', questionIds: ['asha-q2', 'asha-q3', 'asha-q4'], documentIds: ['asha-faa-doc'] },
    { id: 'asha-supplemental-reply', kind: 'supplemental_reply', title: 'Quality and Finance reply', summary: 'A later substantive reply supplies inspection records and a dated no-penalty statement, but no measurement-book extract.', date: '2026-03-15', status: 'Supplemental reply received', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', questionIds: ['asha-q2', 'asha-q3', 'asha-q4'], documentIds: ['asha-supplemental-doc'] },
  ],
  edges: [
    { id: 'asha-e1', from: 'asha-application', to: 'asha-contracts-registration', kind: 'split_to', label: 'Question 1 forwarded' },
    { id: 'asha-e2', from: 'asha-contracts-registration', to: 'asha-contracts-reply', kind: 'replied_with', label: 'Reply received' },
    { id: 'asha-e3', from: 'asha-application', to: 'asha-quality-registration', kind: 'split_to', label: 'Questions 2–4 forwarded' },
    { id: 'asha-e4', from: 'asha-quality-registration', to: 'asha-no-reply', kind: 'no_reply_observed', label: 'No reply by 5 Feb' },
    { id: 'asha-e5', from: 'asha-no-reply', to: 'asha-appeal', kind: 'appealed_as', label: 'First appeal' },
    { id: 'asha-e6', from: 'asha-appeal', to: 'asha-appeal-order', kind: 'ordered', label: 'FAA order' },
    { id: 'asha-e7', from: 'asha-appeal-order', to: 'asha-supplemental-reply', kind: 'supplemented_by', label: 'Later substantive reply' },
  ],
  documents: [
    { id: 'asha-contracts-doc', title: 'Contracts section reply', kind: 'substantive_reply', fileName: 'asha-contracts-reply.pdf', registrationNumber: 'DEMO/CHWD/R/E/26/00810', issuedOn: '2026-01-26' },
    { id: 'asha-faa-doc', title: 'First Appellate Authority order', kind: 'appeal_order', fileName: 'asha-faa-order.pdf', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', issuedOn: '2026-03-04' },
    { id: 'asha-supplemental-doc', title: 'Quality and Finance supplemental reply', kind: 'supplemental_reply', fileName: 'asha-quality-supplemental-reply.pdf', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', issuedOn: '2026-03-15' },
  ],
  mappings: [
    { id: 'asha-map-q1', questionId: 'asha-q1', nodeId: 'asha-contracts-reply', documentId: 'asha-contracts-doc', registrationNumber: 'DEMO/CHWD/R/E/26/00810', coverage: 'answer_located', passage: 'Work Order DEMO-WO-77: Demo Flyover Repair Package 7. Approved contract value: Rs. 48,00,000.', location: 'Pages 1 and 4', confidence: 'high', explanation: 'Both the signed work order and approved value are present.' },
    { id: 'asha-map-q2', questionId: 'asha-q2', nodeId: 'asha-supplemental-reply', documentId: 'asha-supplemental-doc', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', coverage: 'answer_located', passage: 'Inspection dated 18 December 2025 recorded surface cracking in Zones 2 and 3. Core Test DEMO-CT-19 recorded an average result of 31.4 MPa. The signed inspection report and laboratory sheet are enclosed.', location: 'Pages 2–5', confidence: 'high', explanation: 'The later substantive reply encloses both requested record groups.' },
    { id: 'asha-map-q3', questionId: 'asha-q3', nodeId: 'asha-supplemental-reply', documentId: 'asha-supplemental-doc', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', coverage: 'no_matching_passage', confidence: 'low', explanation: 'The supplemental reply was searched, but no measurement-book passage or extract was located.', missingDetail: 'No measurement-book page, extract, or attachment appears in the reply package.' },
    { id: 'asha-map-q4', questionId: 'asha-q4', nodeId: 'asha-supplemental-reply', documentId: 'asha-supplemental-doc', registrationNumber: 'DEMO/CHWD/R/E/26/00810/1', coverage: 'answer_located', passage: 'As of 28 February 2026, no penalty order or payment-deduction order had been issued for Demo Flyover Repair Package 7.', location: 'Page 1', confidence: 'high', explanation: 'The substantive reply contains a dated explicit no-order statement.', temporalQualifier: 'As of 28 February 2026' },
  ],
};
