import {
  COVERAGE_COPY,
  type CaseFixture,
  type CoverageCode,
  type EffectiveMapping,
  type HumanReview,
  type MappingProposal,
} from './domain.ts';

export const DEMO_CASE_DATE = '2026-06-26';
export const REVIEW_STORAGE_KEY = 'rti-reply-map-reviews-v1';

export interface ReviewDraft {
  label: CoverageCode;
  note: string;
}

export function getReviewDraft(
  questionId: string,
  reviews: Record<string, HumanReview | undefined>,
  proposalByQuestion: Record<string, MappingProposal>,
): ReviewDraft {
  const proposal = proposalByQuestion[questionId];
  if (!proposal) throw new Error(`Missing mapping proposal for ${questionId}`);

  const existing = reviews[questionId];
  return {
    label: existing?.selectedLabel ?? proposal.proposedLabel,
    note: existing?.note ?? '',
  };
}

export function summarizeEffectiveMappings(mappings: EffectiveMapping[]) {
  const answersLocated = mappings.filter((mapping) => mapping.effectiveLabel === 'answer_located').length;
  return {
    answersLocated,
    needsChecking: mappings.length - answersLocated,
  };
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

export function createReviewedSummaryHtml(
  fixture: CaseFixture,
  effectiveMappings: EffectiveMapping[],
) {
  const rows = effectiveMappings.map((mapping) => {
    const question = fixture.questions.find((item) => item.id === mapping.questionId);
    if (!question) throw new Error(`Missing question for ${mapping.questionId}`);

    const evidence = fixture.evidence.find((item) => mapping.evidenceIds.includes(item.id));
    const document = fixture.documents.find((item) => item.id === evidence?.documentId);

    return `
      <section>
        <p class="kicker">Question ${question.number}</p>
        <h2>${escapeHtml(question.shortTitle)} — ${escapeHtml(COVERAGE_COPY[mapping.effectiveLabel])}</h2>
        <p>${escapeHtml(question.text)}</p>
        <dl>
          <dt>Suggested label</dt><dd>${escapeHtml(COVERAGE_COPY[mapping.proposedLabel])}</dd>
          <dt>Reviewed label</dt><dd>${escapeHtml(COVERAGE_COPY[mapping.effectiveLabel])}</dd>
          <dt>Related RTI registration number</dt><dd>${escapeHtml(mapping.branchId)}</dd>
          <dt>Reply file</dt><dd>${escapeHtml(document?.fileName ?? 'No reply document')}</dd>
          <dt>Location</dt><dd>${escapeHtml(evidence?.location.label ?? 'No matching passage')}</dd>
        </dl>
        ${evidence ? `<blockquote>${escapeHtml(evidence.quote)}</blockquote>` : ''}
        ${mapping.review?.note ? `<p><strong>Your note:</strong> ${escapeHtml(mapping.review.note)}</p>` : ''}
      </section>`;
  }).join('');

  return `<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>DEMO — Maya's RTI Reply Map</title><style>body{font-family:Arial,sans-serif;max-width:860px;margin:40px auto;padding:0 22px;color:#17352f;line-height:1.55}header{border:3px solid #17352f;padding:22px;margin-bottom:28px}header strong{display:block;color:#8a4b08;font-size:14px;letter-spacing:.05em}section{border-top:1px solid #ccd9d2;padding:24px 0}h1{margin:.2rem 0}.kicker,dt{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#61736e}dl{display:grid;grid-template-columns:220px 1fr;gap:8px}dd{margin:0;font-weight:bold}blockquote{margin:18px 0;padding:16px;border-left:4px solid #1d7355;background:#eef7f1}@media(max-width:600px){dl{grid-template-columns:1fr;gap:2px}dd{margin-bottom:10px}}</style></head><body><header><strong>SYNTHETIC DEMONSTRATION — NOT AN OFFICIAL RECORD</strong><h1>RTI Reply Map</h1><p>Maya's fictional fellowship selection case. Nothing was filed or sent to a government office. This is not legal advice.</p></header>${rows}<footer><p>Generated by an independent hackathon prototype using sample data only.</p></footer></body></html>`;
}
